### ISSUE TITLE
Add Self-hosted models

### ISSUE THREAD

**Issue by fjrdomingues** [fjrdomingues/autopilot#68] opened 2023-04-12 11:55 UTC
**Why**
Users don't want to send their code to OPENAI

**What**
Allow users to connect to different models. Maybe asking users to host the model and provide an API?

**Comment by hatkyinc2** [comment] 2023-04-16 03:34
This is a duplicate of https://github.com/fjrdomingues/autopilot/issues/35
I copied the description over, feel free to edit that one.
General issue cleanup

**Closed by hatkyinc2** 2023-04-16 03:34 UTC
Labels: enhancement, Long term
